nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: false
    paths:
        '^/api1/*':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']
        '^/assets/*':
            allow_origin: [ '*' ]
            allow_headers: [ 'Access-Control-Allow-Origin' ]
            allow_methods: [ 'POST', 'GET' ]