nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api1/*':
            allow_origin: ['(http|https)://(172\.18\.0\.1|localhost|127\.0\.0\.1|xn--c1asiabl5a\.xn--p1ai)(:*)?$']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']