nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST']
        expose_headers: ["Link"]
        max_age: 3600
        forced_allow_origin_value: ~
        skip_same_as_origin: true
