nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Autorization']
        allow_methods: ['GET', 'POST']
        expose_headers: ["Link"]
        max_age: 3600
        forced_allow_origin_value: ~
        skip_same_as_origin: true
