nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['localhost|127.0.0.1|filesky.ru|31.31.192.222|']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
