version: "3.8"

services:
  postgres:
    container_name: postgres-booking
    build:
      context: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - /db-data/:/var/lib/postgresql/data:rw
    networks:
      - booking-net
  php-fpm:
    container_name: php-fpm-booking
    build:
      context: ./php-fpm
      args:
        - PUID=1000
        - PGID=1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"

    volumes:
      - ./../:/var/www/
      - /etc/letsencrypt/:/etc/letsencrypt/
#      - ./php-fpm/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - booking-net
    ports:
      - 8282:80

networks:
  booking-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "docker_booking"

volumes:
  db_data:
