name: Build and Deploy

on:
  push:
    branches: [ v2.0_dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.megasecretfile }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Deploy
      #- run: cd app && rsync -e "ssh -p 38125 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . m71516@hostru04.fornex.org:/var/web-prg/test-rsync
      - run: ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes webuser@31.31.192.222 -p38125 'cd /var/web-prg/gcppmsp && _pullc'