name: Build and Deploy

on:
  push:
    branches: [ v2.0_dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          private_key: ${{secrets.MEGASECRETFILE}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }}
            _pullc