# This is a basic workflow that is manually triggered

name: Auto Work

on:
  push:
    branches: [ v2.0_dev ]
  pull_request:
    branches: [ v2.0_dev  ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: cd /var/www/gcppmsp && _pullc