# This is a basic workflow that is manually triggered

name: Auto Work

on:
  push:
    branches: [ prod]
  pull_request:
    branches: [ prod ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/web-prg/gcppmsp
            git pull
            docker-compose -f docker/docker-compose.yml exec -u www-data php-fpm php bin/console cache:clear